### ISSUE TITLE
Meshstatic

### ISSUE THREAD

**Issue by xor256** [SudoMaker/Notkia#1]
Is possible add https://meshtastic.org/ protocol / softweare to notkia?

**Comment by ClassicOldSong** [comment]
I don't see why not. Notkia runs Linux with standard SPI interface and standard SX126x chip for LoRa, you should be able to migrate it's protocol and software to this platform rather easy.

**Comment by sp00ck** [comment]
Better way is Reticullum. Only python is needed
https://reticulum.network/  and guides https://unsigned.io/guides.html

**Comment by ReimuNotMoe** [comment]
> Better way is Reticullum. Only python is needed https://reticulum.network/ and guides https://unsigned.io/guides.html

Do you know how much RAM does it use?
